### ISSUE TITLE
Channel selection broken for (at least) NP 1.0 probes

### ISSUE THREAD

**Issue by pbotros** [open-ephys-plugins/neuropixels-pxi#20]
Hi, it seems like the latest versions of the neuropixels-pxi does not actually select channels properly for (at least) NP 1.0 probes, despite the OpenEphys GUI indicating that it was successful and no indicative error messages in the console. Methodology:

I hooked the NP up to a signal generator as mentioned in the Neuropixel User Manual for testing signal, dipped the bottom ~1/3 of the probe into PBS, and performed multiple recordings across all possible recording sites. Surprisingly, despite selecting different channels both via IMRO upload and via manual selection in the GUI, all combinations yielded signal reflective of the signal generator (i.e. a ~1.8 kHz sine wave). This reproduced on all tagged GitHub releases from 0.2.0 to the most recent (0.3.1). Critically, I then reverted back to version 0.1.0 and repeated the same test (without touching the probe or experimental setup), and the signal looked as was expected: only about ~1/3 of the channels showed signal from the signal generator, with the rest closer to zero.

I repeated this with a different pair of probe and headstage, and the same problem reproduced on the later versions of this plugin, and was cured with the older 0.1.0 version of the plugin.

If someone else can confirm this independently to make sure I'm not doing anything dumb, that would be great, as otherwise I would imagine this bug would be fairly detrimental to any recordings done in the past ~6 months / might warrant some form of broadcast to participating labs.

Thanks!

**Comment by jsiegle** [comment]
Which version of the basestation firmware are you using? This is listed on the right side of the probe settings interface, underneath the API version.

**Comment by pbotros** [comment]
Looks like 1.0.151 .

**Comment by jsiegle** [comment]
Ok, that makes sense. Version 1.0.X is the only version that would have been compatible with plugin 0.1.0.

First of all, thanks for doing these tests! It sounds like you've carried out all the right steps to verify the problem.

My guess is that the issue could be due to one of two things:
1. In plugin 0.1.0, we were disconnecting every channel before selecting the active channels (code available [here](https://github.com/open-ephys-plugins/neuropixels-pxi/blob/ec218aaf0776c1d10be8d1bd3e83ee5aea721fde/NeuropixPlugin/NeuropixPlugin/NeuropixComponents.cpp#L216-L275)). In 0.2.0+, only the active channels are being selected (code available [here](https://github.com/open-ephys-plugins/neuropixels-pxi/blob/80d18045cc7b7fb45fa439931445fade3eecc27d/Source/Probes/Neuropixels1_v1.cpp#L216-L233)). It's possible this function is not able to override channels that are already selected (although this would be undocumented behavior).
2. There is an uncaught indexing issue that's causing the `selectedBank` on [this line](https://github.com/open-ephys-plugins/neuropixels-pxi/blob/80d18045cc7b7fb45fa439931445fade3eecc27d/Source/Probes/Neuropixels1_v1.cpp#L227) to always default to 0.

@medengineer, can you add some debug output to check (2), and then generate a version of the plugin that re-instates the channel disconnections described in (1)?

**Comment by pbotros** [comment]
@medengineer any luck with reproducing this bug? We were "lucky" in the sense that we caught this bug only after doing a ~couple weeks of behavior with a test rat, but I can imagine other labs over the past ~6 months might not be so lucky and could inadvertently be using misleading data. We could also use the IMRO save/load function that's present in recent branches, so fixing it upstream would be preferable to having to backport that functionality to 0.1.0.

Thanks!

**Comment by jsiegle** [comment]
We were able to replicate this with saline tests. It looks like it's only an issue for the 1.0.X firmware, so those using upgraded firmware won't be affected. The problem is most likely due to reason 1 (not disconnecting the channels before selecting a new bank). We will release a corrected version and send out an announcement in the next few days.

**Comment by pbotros** [comment]
Great, thanks @jsiegle !

**Comment by jsiegle** [comment]
FYI the latest version of the plugin (0.3.2) has this fix implemented. Let us know if you get a chance to test it out!

**Comment by pbotros** [comment]
@jsiegle @medengineer 0.3.2 seems to fix the channel selection problem for me, both on my existing 1.0.X firmware and after upgrading my basestation firmware to the latest. Thanks for the quick fix!
